services:
  db:
    image: postgres:17.0-bookworm-koKR
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-platform-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: shopadmin
      POSTGRES_PASSWORD: ${LOCAL_DEVDB_SUPER_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: "OrderingDB:shopuser, SellersDB:shopuser, OrderingDB_Testing:testuser, SellersDB_Testing:testuser, SellersDB_Isolated:testuser"
      POSTGRES_MULTIPLE_INIT_PASSWORD: ${LOCAL_DEVDB_PASSWORD}
      LANG: ko_KR.UTF-8
    volumes:
      - ./init.sh:/init.sh
      - shop-platform-db-data:/var/lib/postgresql/data
    entrypoint: ["/bin/bash", "-c", "/init.sh & exec docker-entrypoint.sh postgres"]
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "40080:8080"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.32.0-arm64
    container_name: "ordering-azurite"
    restart: always
    ports:
      - "10001:10001"
#   컨테이너가 아닌 경우 0.0.0.0 원격 호스트는 주의해서 사용한다.
    command: azurite-queue --queueHost 0.0.0.0 --queuePort 10001
    volumes:
      - ordering-azurite-data:/data
      
volumes:
  shop-platform-db-data:
  ordering-azurite-data: