services:
  ordering-db:
    image: postgres:17.0-bookworm-koKR
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ordering-db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: ${LOCAL_ORDERDB_PASSWORD}
      POSTGRES_DB: OrderingDB
      LANG: ko_KR.UTF-8
    volumes:
      - ordering-db-data:/var/lib/postgresql/data
      # - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  ordering-test-db:
    image: postgres:17.0-bookworm-koKR
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ordering-test-db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: ${LOCAL_ORDERDB_PASSWORD}
      POSTGRES_DB: OrderingDB_Testing
      LANG: ko_KR.UTF-8
    volumes:
      - ordering-test-db-data:/var/lib/postgresql/data
      # - ./data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "40080:8080"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.32.0-arm64
    container_name: "ordering-azurite"
    restart: always
    ports:
      - "10001:10001"
#   컨테이너가 아닌 경우 0.0.0.0 원격 호스트는 주의해서 사용한다.
    command: azurite-queue --queueHost 0.0.0.0 --queuePort 10001
    volumes:
      - ordering-azurite-data:/data
      
volumes:
  ordering-db-data:
  ordering-test-db-data:
  ordering-azurite-data: