services:
  postgres-17.0:
    image: postgres:17.0-bookworm-koKR
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-17.0
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: ${LOCAL_ORDERDB_PASSWORD}
      POSTGRES_DB: shopdb
      LANG: ko_KR.UTF-8
    volumes:
      - postgres17.0-data:/var/lib/postgresql/data
      # - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 40080:8080

volumes:
  postgres17.0-data: